FROM us-central1-docker.pkg.dev/sara-soverigne-modules/sara-quantum-defense/raft-node-pqc@sha256:7ff920d41bfd5da2e070f1b94bffee668979b672295d49e14a7b889036e72688
COPY main_patched_raft.py /app/main_patched_raft.py
CMD ["gunicorn", "--bind", ":8080", "--workers", "1", "--threads", "8", "--worker-class", "gthread", "main_patched_raft:app"]
